version: '3'

services:
  concourse-db:
    image: postgres:9.5
    volumes:
      - /var/lib/data/skills/concourse/postgresql:/database
    restart: unless-stopped
    environment:
      POSTGRES_DB: concourse
      POSTGRES_USER: concourse
      POSTGRES_PASSWORD: changeme
      PGDATA: /database

  concourse-web:
    image: concourse/concourse
    links: [concourse-db]
    command: web
    depends_on: [concourse-db]
    ports: ["8080:8080"]
    volumes:
      - /var/lib/data/skills/concourse/keys/web:/concourse-keys
    restart: unless-stopped
    environment:
      CONCOURSE_BASIC_AUTH_USERNAME: concourse
      CONCOURSE_BASIC_AUTH_PASSWORD: changeme
      CONCOURSE_EXTERNAL_URL: "http://127.0.0.1:8080"
      CONCOURSE_POSTGRES_HOST: concourse-db
      CONCOURSE_POSTGRES_USER: concourse
      CONCOURSE_POSTGRES_PASSWORD: changeme
      CONCOURSE_POSTGRES_DATABASE: concourse

  concourse-worker:
    image: concourse/concourse
    restart: unless-stopped
    privileged: true
    links: [concourse-web]
    depends_on: [concourse-web]
    command: worker
    volumes:
      - /var/lib/data/skills/concourse/keys/worker:/concourse-keys
    environment:
      CONCOURSE_TSA_HOST: concourse-web
