apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gateway
  annotations:
    kubernetes.io/ingress.class: "istio"
spec:
  rules:
  - http:
      paths:
      - path: /graph.?ql/.*
        backend:
          serviceName: skills-api
          servicePort: 3000
---
