#!/bin/sh
set -e

OVERRIDE_CLUSTER_NAME=${CLUSTER_NAME}
set -u -a
. ./.env
set +a

CLUSTER_NAME=${OVERRIDE_CLUSTER_NAME:-$CLUSTER_NAME}
enable_alpha_features=""
machine_type="n1-standard-1"

if [ ${ALPHA_CLUSTER} = true ]; then
  enable_alpha_features="--enable-kubernetes-alpha --no-enable-legacy-authorization"
fi

echo gcloud container clusters create "${CLUSTER_NAME}" \
    --cluster-version=${KUBERNETES_VERSION} \
    ${enable_alpha_features} \
    --machine-type="${machine_type}" \
    --num-nodes="${CLUSTER_SIZE}" \
    --zone="${CLUSTER_ZONE}"

gcloud container clusters get-credentials "${CLUSTER_NAME}" --zone "${CLUSTER_ZONE}" --project "${GCLOUD_PROJECT_NAME}"
kubectl create clusterrolebinding cluster-admin-binding --clusterrole=cluster-admin --user=$(gcloud config get-value core/account)
