#!/bin/sh
set -e

OVERRIDE_CONCOURSE_EXTERNAL_URL=${CONCOURSE_EXTERNAL_URL}
set -u -a
. ./.env
set +a

export CONCOURSE_EXTERNAL_URL=${OVERRIDE_CONCOURSE_EXTERNAL_URL:-$CONCOURSE_EXTERNAL_URL}
keys_dir="./legacy/data/concourse/keys"

rm -Rf "${keys_dir}"
mkdir -p "${keys_dir}/web" "${keys_dir}/worker"
ssh-keygen -t "rsa" -f "${keys_dir}/web/tsa_host_key" -N ""
ssh-keygen -t "rsa" -f "${keys_dir}/web/session_signing_key" -N ""

ssh-keygen -t "rsa" -f "${keys_dir}/worker/worker_key" -N ""

cp ${keys_dir}/worker/worker_key.pub ${keys_dir}/web/authorized_worker_keys
cp ${keys_dir}/web/tsa_host_key.pub ${keys_dir}/worker

echo "To view in your browser:"
echo "ATC URL: ${CONCOURSE_EXTERNAL_URL}\nusername: concourse\n password: changeme"
echo "To view aggregate:"
echo "$ docker-compose logs -f"
docker-compose -f ./legacy/concourse/docker-compose.yml up -d --force-recreate
sudo wget "http://ci.concourse.ci/api/v1/cli?arch=amd64&platform=linux" -r -O /usr/local/bin/fly
sudo chmod +x /usr/local/bin/fly
fly -t local login --concourse-url="${CONCOURSE_EXTERNAL_URL}" -u concourse -p changeme
sudo fly -t local sync
